version: "3.9"

networks:
  dockerapi-dev:
    driver: bridge

services:
  weather-1:      
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"

    networks:
      - dockerapi-dev

  weather-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8082"

    networks:
      - dockerapi-dev

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weather-1
      - weather-2
    ports:
      - "4000:4000"
    networks:
      - dockerapi-dev

 